import type { FlatConfig } from '../common'
import globals from 'globals'

/**
 * 此处包含了 javascript 相关规则
 * 由于 eslint 不再维护样式类规则, 此处样式配置应使用 eslint stylistic 提供的规则
 */
export function javascriptFactory(): FlatConfig {
  return {
    name: 'javascript',
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.es2021,
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      // -------- Possible Problems --------
      'array-callback-return': 'warn',
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'off',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'warn',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-constructor-return': 'warn',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'off',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-ex-assign': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'warn',
      'no-new-symbol': 'error',
      'no-obj-calls': 'error',
      'no-promise-executor-return': 'warn',
      'no-prototype-builtins': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'warn',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'off',
      'no-this-before-super': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'warn',
      'no-unreachable': 'error',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-private-class-members': 'warn',
      'no-unused-vars': 'error',
      'no-use-before-define': 'warn',
      'no-useless-backreference': 'error',
      'require-atomic-updates': 'warn',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // -------- Suggestions --------
      'accessor-pairs': 'warn',
      'arrow-body-style': 'off',
      'block-scoped-var': 'warn',
      'camelcase': 'off',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      'complexity': 'warn',
      'consistent-return': 'off',
      'consistent-this': ['warn', 'self'],
      'curly': 'off',
      'default-case': 'off',
      'default-case-last': 'warn',
      'default-param-last': 'warn',
      'dot-notation': 'off',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'func-name-matching': 'off',
      'func-names': 'off',
      'func-style': 'off',
      'grouped-accessor-pairs': ['warn', 'getBeforeSet'],
      'guard-for-in': 'warn',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'init-declarations': ['warn', 'always'],
      'logical-assignment-operators': 'off',
      'max-classes-per-file': 'off',
      'max-depth': 'warn',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': ['warn', 3],
      'max-params': 'off',
      'max-statements': 'off',
      'multiline-comment-style': 'off',
      'new-cap': 'warn',
      'no-alert': 'off',
      'no-array-constructor': 'warn',
      'no-bitwise': 'off',
      'no-caller': 'warn',
      'no-case-declarations': 'error',
      'no-console': 'off',
      'no-continue': 'off',
      'no-delete-var': 'error',
      'no-div-regex': 'warn',
      'no-else-return': 'warn',
      'no-empty': 'error',
      'no-empty-function': 'warn',
      'no-empty-static-block': 'warn',
      'no-eq-null': 'off',
      'no-eval': 'off',
      'no-extend-native': 'warn',
      'no-extra-bind': 'warn',
      'no-extra-boolean-cast': 'error',
      'no-extra-label': 'warn',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'off',
      'no-implied-eval': 'warn',
      'no-inline-comments': 'off',
      'no-invalid-this': 'warn',
      'no-iterator': 'warn',
      'no-label-var': 'warn',
      'no-labels': 'off',
      'no-lone-blocks': 'warn',
      'no-lonely-if': 'warn',
      'no-loop-func': 'warn',
      'no-magic-numbers': 'off',
      'no-multi-assign': 'warn',
      'no-multi-str': 'warn',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'warn',
      'no-new': 'warn',
      'no-new-func': 'warn',
      'no-new-wrappers': 'warn',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'warn',
      'no-octal': 'error',
      'no-octal-escape': 'warn',
      'no-param-reassign': 'warn',
      'no-plusplus': ['warn', { allowForLoopAfterthoughts: true }],
      'no-proto': 'warn',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'no-return-assign': 'warn',
      'no-script-url': 'warn',
      'no-sequences': 'warn',
      'no-shadow': 'warn',
      'no-shadow-restricted-names': 'error',
      'no-ternary': 'off',
      'no-throw-literal': 'warn',
      'no-undef-init': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'warn',
      'no-unused-expressions': 'warn',
      'no-unused-labels': 'error',
      'no-useless-call': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-constructor': 'warn',
      'no-useless-escape': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'warn',
      'no-void': 'off',
      'no-warning-comments': 'off',
      'no-with': 'error',
      'object-shorthand': 'off',
      'one-var': 'off',
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': 'off',
      'prefer-exponentiation-operator': 'warn',
      'prefer-named-capture-group': 'warn',
      'prefer-numeric-literals': 'warn',
      'prefer-object-has-own': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'prefer-regex-literals': 'warn',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'prefer-template': 'warn',
      'radix': 'warn',
      'require-await': 'warn',
      'require-unicode-regexp': 'warn',
      'require-yield': 'error',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      'strict': 'off',
      'symbol-description': 'warn',
      'vars-on-top': 'warn',
      'yoda': ['warn', 'never'],

      // -------- Layout & Formatting --------
      'line-comment-position': 'off',
      'unicode-bom': 'warn',
    },
  }
}
